# fly.toml app configuration file generated for music-contact on 2023-05-13T19:43:05+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "music-contact"
primary_region = "mad"

[env]
  SESSION_SECURE='false'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
